// The AuthFlow.Domain.Entities namespace contains all the entity classes used in the authentication flow of the application.
namespace AuthFlow.Domain.Entities
{
    // The TokenResponse class represents a response from a token generating service such as an OAuth or JWT service.
    // Instances of this class are used to encapsulate the generated token so it can be easily sent to the client.
    public class TokenResponse
    {
        // The Token property represents an authentication or authorization token generated by the service.
        // This is typically a string encoded in a certain format (like JWT) that contains information 
        // about the authenticated user, and it can be used to authorize further requests from the client.
        public string Token { get; set; }
    }
}
