//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthFlow.Infraestructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthFlow.Infraestructure.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user is already registered with this email..
        /// </summary>
        internal static string FailedAlreadyRegisteredEmail {
            get {
                return ResourceManager.GetString("FailedAlreadyRegisteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user is already registered with this username..
        /// </summary>
        internal static string FailedAlreadyRegisteredUser {
            get {
                return ResourceManager.GetString("FailedAlreadyRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more data from the User have been submitted with errors {0}.
        /// </summary>
        internal static string FailedDataSizeCharacter {
            get {
                return ResourceManager.GetString("FailedDataSizeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the data layer..
        /// </summary>
        internal static string FailedOccurredDataLayer {
            get {
                return ResourceManager.GetString("FailedOccurredDataLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} you are trying to active does not exist..
        /// </summary>
        internal static string GenericToActiveNotExist {
            get {
                return ResourceManager.GetString("GenericToActiveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} you are trying to delete does not exist..
        /// </summary>
        internal static string GenericToDeleteNotExist {
            get {
                return ResourceManager.GetString("GenericToDeleteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The{0} you are trying to inactive does not exist..
        /// </summary>
        internal static string GenericToInactiveNotExist {
            get {
                return ResourceManager.GetString("GenericToInactiveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary data was not provided..
        /// </summary>
        internal static string NecesaryData {
            get {
                return ResourceManager.GetString("NecesaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was created successfully..
        /// </summary>
        internal static string SuccessfullyGeneric {
            get {
                return ResourceManager.GetString("SuccessfullyGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was activated successfully..
        /// </summary>
        internal static string SuccessfullyGenericActiveated {
            get {
                return ResourceManager.GetString("SuccessfullyGenericActiveated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deleted successfully..
        /// </summary>
        internal static string SuccessfullyGenericDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyGenericDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was disabled successfully..
        /// </summary>
        internal static string SuccessfullyGenericDisabled {
            get {
                return ResourceManager.GetString("SuccessfullyGenericDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was updated successfully..
        /// </summary>
        internal static string SuccessfullyGenericUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyGenericUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search in the {0} entity completed successfully..
        /// </summary>
        internal static string SuccessfullySearchGeneric {
            get {
                return ResourceManager.GetString("SuccessfullySearchGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search in the User entity completed successfully..
        /// </summary>
        internal static string SuccessfullySearchUser {
            get {
                return ResourceManager.GetString("SuccessfullySearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was created successfully..
        /// </summary>
        internal static string SuccessfullyUser {
            get {
                return ResourceManager.GetString("SuccessfullyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was activated successfully..
        /// </summary>
        internal static string SuccessfullyUserActiveated {
            get {
                return ResourceManager.GetString("SuccessfullyUserActiveated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was deleted successfully..
        /// </summary>
        internal static string SuccessfullyUserDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was disabled successfully..
        /// </summary>
        internal static string SuccessfullyUserDisabled {
            get {
                return ResourceManager.GetString("SuccessfullyUserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was updated successfully..
        /// </summary>
        internal static string SuccessfullyUserUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to active does not exist..
        /// </summary>
        internal static string UserToActiveNotExist {
            get {
                return ResourceManager.GetString("UserToActiveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to delete does not exist..
        /// </summary>
        internal static string UserToDeleteNotExist {
            get {
                return ResourceManager.GetString("UserToDeleteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to inactive does not exist..
        /// </summary>
        internal static string UserToInactiveNotExist {
            get {
                return ResourceManager.GetString("UserToInactiveNotExist", resourceCulture);
            }
        }
    }
}
